name: Build and Test Node.js Project

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build Docker image
        if: success()
        run: |
          docker build -t devops-lab .
          docker tag devops-lab ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to Docker Hub
        if: success()
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ github.sha }}

      - name: Pull and curl
        if: success()
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
          docker run -d -p 80:80 --name my-node-app ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
          sleep 5
          curl -I http://localhost:80 | grep "200 OK"